"""empty message

Revision ID: 79d250df7628
Revises: 9f8c33e763e5
Create Date: 2017-12-28 08:11:06.324802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d250df7628'
down_revision = '9f8c33e763e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entries', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='unique')
    # ### end Alembic commands ###
