"""empty message

Revision ID: 9f8c33e763e5
Revises: 25f7d130096d
Create Date: 2017-12-28 08:05:09.631412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8c33e763e5'
down_revision = '25f7d130096d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('authors', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('content', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('journal', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('link', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('published', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('title', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('volume', sa.String(), nullable=True))
    op.drop_column('entries', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'volume')
    op.drop_column('entries', 'title')
    op.drop_column('entries', 'published')
    op.drop_column('entries', 'link')
    op.drop_column('entries', 'journal')
    op.drop_column('entries', 'content')
    op.drop_column('entries', 'authors')
    # ### end Alembic commands ###
